'use strict';
const questions=[
{title:'В какой ситуации ты хочешь сдвинуться?',hint:'Выбери одну область. Дальше отвечай только про неё.',options:['Развить бизнес или вырасти в доходе','Запустить новый проект','Изменить работу или свою роль','Освободить время и снизить нагрузку','Вернуть интерес к тому, что делаю']},
{title:'Какое изменение пока не получилось?',hint:'Одно конкретное предложение. Например: «Хочу передать продажи команде, но всё ещё веду каждого клиента сам».',text:true},
{title:'Что было в последней попытке?',hint:'Вспомни, чем закончилась именно она.',options:['Долго готовился, но так и не проверил идею в деле','Начал активно, потом не выдержал темп','Переключился на другую задачу или идею','Получил результат, но он меня не порадовал','Упёрся в нехватку денег, времени, навыков или информации'],scores:['start','load','focus','meaning','external'],weight:2},
{title:'Что чаще происходит в момент затруднения?',hint:'Выбери наиболее знакомую реакцию.',options:['Ищу ещё информацию, улучшаю, откладываю проверку','Беру ещё больше на себя и работаю дольше','Ищу другой путь и начинаю что-то новое','Делаю через «надо», хотя уже не понимаю зачем','Ищу недостающий ресурс или конкретную помощь'],scores:['start','load','focus','meaning','external'],weight:1},
{title:'Какая мысль ближе всего?',hint:'Она не обязана описывать тебя всегда — только эту ситуацию.',options:['Сначала нужно быть полностью готовым','Без моего участия всё развалится','Другой вариант может оказаться лучше','Я должен этого хотеть, но не очень хочу','Пока нет нужных условий для следующего шага'],scores:['start','load','focus','meaning','external'],weight:1},
{title:'Что ты уже пробовал менять?',hint:'Речь о действиях, а не о намерениях.',options:['Ещё учился и улучшал план','Увеличивал усилия и время работы','Менял инструменты, задачи или направление','Ставил новую цель, чтобы вернуть интерес','Закрывал конкретную нехватку ресурсов'],scores:['start','load','focus','meaning','external'],weight:1},
{title:'Что повторяется дольше всего?',hint:'Этому ответу мы дадим больший вес: он описывает наблюдаемый результат.',options:['Важное действие всё ещё не сделано','После рывка приходится долго восстанавливаться','Много начинаний, мало завершённых проверок','Достижения есть, удовлетворения всё меньше','Одна и та же нехватка мешает двигаться'],scores:['start','load','focus','meaning','external'],weight:2},
{title:'Как часто это уже происходило?',hint:'Если это первый случай, пока рано считать его устойчивым сценарием.',options:['Впервые — хочу разобраться заранее','Два-три раза в похожих задачах','Регулярно, в разных ситуациях','Не уверен — раньше не отслеживал']}
];
const profiles={
start:{title:'Между подготовкой и действием',name:'Подготовка заменяет проверку',intro:'В ответах чаще повторяется ожидание готовности. Возможно, полезный поворот сейчас — получить небольшой реальный опыт раньше, чем появится уверенность.',chain:['Есть идея','Нужно подготовиться','Проверка откладывается','Новой ясности нет'],body:'Дополнительная подготовка полезна, когда закрывает конкретный пробел. Но если критерий «готов» постоянно сдвигается, ты остаёшься без обратной связи. Проверь, что можно узнать маленьким действием.',experiment:'Одна безопасная проверка вместо ещё одного плана',steps:['Выбери один вопрос, на который не ответит дальнейшее чтение. Например: понимают ли потенциальные клиенты моё предложение?','Сделай минимальную проверку: один разговор, черновик для обратной связи или пробный показ. Заранее ограничь время и возможные потери.','В течение 48 часов проведи проверку и запиши факт: что оказалось так, а что иначе.'],criterion:'Одна проверка проведена и получено одно новое наблюдение. Успешная продажа или идеальный результат не обязательны.'},
load:{title:'Рост через постоянный перегруз',name:'Рывок сменяется откатом',intro:'По ответам усилия накапливаются быстрее, чем возможность восстанавливаться. Стоит проверить, можно ли удержать движение с меньшей нагрузкой.',chain:['Беру больше','Тащу на себе','Перегружаюсь','Снижаю темп'],body:'Ты умеешь включаться и добиваться результата. Вопрос в том, насколько этот способ можно повторять. Здесь полезно проверить не силу воли, а устройство нагрузки: что действительно требует твоего участия?',experiment:'Освободи место для одного важного действия',steps:['Выпиши три задачи, которые забирают много времени. Выбери одну с невысокой ценой ошибки.','На 48 часов убери её, сократи объём или передай с ясным критерием готовности и одной точкой проверки. Учитывай обязательства перед другими.','Используй освободившееся время на один посильный шаг по своей цели. Зафиксируй, что произошло с результатом и нагрузкой.'],criterion:'Одна задача стала легче или перестала требовать твоего участия. Записано, что удалось сохранить в результате.'},
focus:{title:'Движение без завершённой проверки',name:'Новый вариант обнуляет предыдущий',intro:'В ответах заметно переключение между направлениями. Следующая полезная проба — остаться с одной задачей достаточно долго, чтобы получить данные.',chain:['Выбираю направление','Встречаю сложность','Нахожу новую идею','Начинаю заново'],body:'Смена направления иногда необходима. Но без критерия остановки трудно отличить обоснованный поворот от ухода при первых затруднениях. Дай одной небольшой гипотезе короткий срок и ясный результат.',experiment:'Одна гипотеза. Один срок. Один вывод.',steps:['Выбери одну гипотезу, которую реально проверить за 48 часов. Например: три разговора помогут уточнить, понятна ли услуга.','Определи, какое наблюдение будет доводом продолжить, изменить или остановить проверку. Остальные идеи запиши отдельно.','Доведи эту проверку до конца и подведи итог по фактам. При существенных новых рисках пересмотри план, а не следуй ему вслепую.'],criterion:'Есть законченная проверка и решение на основании наблюдений, даже если гипотеза не подтвердилась.'},
meaning:{title:'Результат, который больше не вдохновляет',name:'Движение по инерции',intro:'Ответы указывают на разрыв между привычной целью и тем, что важно тебе сейчас. Начни с уточнения желаемого изменения в повседневной жизни.',chain:['Ставлю привычную цель','Делаю через «надо»','Достигаю или откладываю','Интерес не возвращается'],body:'Цель могла подходить раньше и перестать подходить сейчас. Это гипотеза, которую стоит проверить на конкретном опыте. Не нужно принимать большое решение только из-за результата этого разбора.',experiment:'Проверь, ради чего тебе следующий результат',steps:['Закончи фразу: «Если я достигну цели, в моём обычном дне изменится…». Назови конкретное изменение, а не статус.','Выбери маленький обратимый способ попробовать это изменение уже сейчас: час иной работы, разговор о новой роли или время без рабочих сообщений.','В течение 48 часов проведи пробу. Запиши, что действительно хотелось повторить и что оказалось лишь красивой идеей.'],criterion:'Есть одно наблюдение о том, какой опыт тебе важен. На его основе можно уточнить цель, сохранив текущие обязательства.'},
external:{title:'Сначала — конкретное ограничение',name:'Для следующего шага не хватает опоры',intro:'В ответах чаще фигурирует нехватка ресурсов или условий. Нет оснований автоматически объяснять её внутренним «стопором». Сначала стоит уточнить сам пробел.',chain:['Есть цель','Не хватает ресурса','Шаг недоступен','Задача остаётся'],body:'Информация, время, навыки и деньги могут быть реальными ограничениями. Раздели необходимое и желательное. Иногда достаточно уменьшить масштаб первой пробы; иногда разумно отложить её до появления условий.',experiment:'Уточни один пробел и способ его закрыть',steps:['Назови один недостающий ресурс максимально конкретно: какая информация, навык, время или помощь нужны?','Проверь минимальный объём: можно ли уменьшить задачу или провести пробу с тем, что уже есть? Не принимай финансовых обязательств ради эксперимента.','За 48 часов сделай одно действие для ясности: запроси условия, найди человека с нужным опытом или оцени необходимые затраты времени.'],criterion:'Ограничение описано точнее и выбран реалистичный следующий шаг — либо ясное условие, при котором вернёшься к задаче.'}
};
let step=0, answers=Array(8).fill(null), current=null;
const $=id=>document.getElementById(id);
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function track(name,data={}){window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:name,...data});}
function show(id){['home','quiz','result'].forEach(x=>$(x).hidden=x!==id);window.scrollTo({top:0,behavior:'instant'});}
function valid(){return questions[step].text?typeof answers[step]==='string'&&answers[step].trim().length>=8:Number.isInteger(answers[step]);}
function render(){const q=questions[step];$('step-count').textContent=`ВОПРОС ${step+1} ИЗ 8`;$('progress-fill').style.width=`${(step+1)/8*100}%`;document.querySelector('.progress').setAttribute('aria-valuenow',step+1);$('question-content').innerHTML=`<h2 tabindex="-1" id="question-title">${q.title}</h2><p>${q.hint}</p>`+(q.text?`<label for="goal">Моя ситуация</label><textarea id="goal" rows="4" maxlength="600" placeholder="Хочу… но пока…">${escapeHTML(answers[step]||'')}</textarea><p class="small">От 8 до 600 символов. Личные подробности можно не указывать.</p>`:`<fieldset class="options" aria-labelledby="question-title">${q.options.map((o,i)=>`<label class="option"><input type="radio" name="answer" value="${i}" ${answers[step]===i?'checked':''}><span>${o}</span></label>`).join('')}</fieldset>`);$('next').disabled=!valid();$('back').disabled=step===0;$('next').innerHTML=step===7?'Увидеть мою карту <span>↗</span>':'Дальше <span>→</span>';if(q.text)$('goal').addEventListener('input',e=>{answers[step]=e.target.value;$('next').disabled=!valid()});else document.querySelectorAll('input[name=answer]').forEach(el=>el.addEventListener('change',e=>{answers[step]=Number(e.target.value);$('next').disabled=false}));$('question-title').focus({preventScroll:true});}
function calculate(){const score={start:0,load:0,focus:0,meaning:0,external:0};for(let i=2;i<=6;i++)score[questions[i].scores[answers[i]]]+=questions[i].weight;const order=Object.keys(score).sort((a,b)=>score[b]-score[a]||(questions[6].scores[answers[6]]===a?-1:questions[6].scores[answers[6]]===b?1:0));return {key:order[0],score,mixed:score[order[0]]-score[order[1]]<=1,second:order[1]};}
function finish(){current=calculate();const p=profiles[current.key];$('result-title').textContent=p.title;$('result-intro').textContent=p.intro;$('pattern-title').textContent=p.name;$('goal-view').textContent=answers[1];$('chain').innerHTML=p.chain.map(x=>`<span>${x}</span>`).join('<b aria-hidden="true">→</b>');$('pattern-body').textContent=p.body;$('experiment-title').textContent=p.experiment;$('experiment').innerHTML=p.steps.map(x=>`<li>${x}</li>`).join('');$('criterion').textContent=p.criterion;$('evidence').innerHTML=[2,3,4,5,6].filter(i=>questions[i].scores[answers[i]]===current.key).map(i=>`<li>${questions[i].options[answers[i]]}</li>`).join('');$('mixed').textContent=(answers[7]===0||answers[7]===3?'Повторение пока не подтверждено: воспринимай карту как гипотезу по одному случаю. ':'')+(current.mixed?`Ответы смешанные. Также заметна тема «${profiles[current.second].name.toLowerCase()}». Начни с предложенной проверки и сравни с опытом.`:'Это наиболее заметная тема в ответах, а не постоянная характеристика тебя.');show('result');$('result-title').setAttribute('tabindex','-1');$('result-title').focus({preventScroll:true});track('assessment_completed',{pattern:current.key});}
function report(){const p=profiles[current.key];return `СЛЕДУЮЩИЙ ШАГ — Тимофей Бараковский\n\nМОЯ СИТУАЦИЯ\n${answers[1]}\n\nГИПОТЕЗА\n${p.name}\n${p.chain.join(' → ')}\n${$('mixed').textContent}\n\nПОЧЕМУ\n${$('evidence').innerText}\n\nЭКСПЕРИМЕНТ НА 48 ЧАСОВ\n${p.steps.map((x,i)=>`${i+1}. ${x}`).join('\n')}\n\nКРИТЕРИЙ\n${p.criterion}\n\nМОЙ ШАГ\n${$('action').value||'Ещё не записан'}\nКОГДА\n${$('when').value.replace('T',' ')||'Ещё не выбрано'}\nПОЙМУ, ЧТО СДЕЛАЛ, КОГДА\n${$('success').value||'Ещё не записано'}\n\nЭто практика самоанализа, а не психологическая диагностика.\n`;}
function start(){show('quiz');render();track('assessment_started');}
$('start').onclick=start;$('exit').onclick=()=>show('home');document.querySelector('.brand').onclick=e=>{e.preventDefault();show('home')};document.querySelector('.about-link').onclick=()=>show('home');$('next').onclick=()=>{if(!valid())return;if(step===7)finish();else{step++;render()}};$('back').onclick=()=>{if(step>0){step--;render()}};$('edit').onclick=()=>{step=0;start()};$('reset').onclick=()=>{if(answers.some(x=>x!==null)&&!window.confirm('Начать заново? Текущие ответы и план будут удалены из этой вкладки.'))return;answers=Array(8).fill(null);step=0;current=null;['action','when','success'].forEach(x=>$(x).value='');show('home')};$('download').onclick=()=>{const blob=new Blob(['\uFEFF'+report()],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='Мой следующий шаг.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('save-status').textContent='Карта подготовлена к скачиванию. Проверь загрузки браузера.';track('result_downloaded',{pattern:current.key})};$('print').onclick=()=>window.print();$('offer-link').onclick=()=>track('offer_clicked',{pattern:current?.key});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_assessment_state',description:'Read the current assessment question and available choices, without submitting answers.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({screen:!$('result').hidden?'result':!$('quiz').hidden?'quiz':'home',question:step+1,title:questions[step].title,options:questions[step].options||null,result:current?profiles[current.key].name:null})})).catch(()=>{});}catch{}}
